name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Hostinger
        run: |
          ssh u376338418@88.223.85.159 "rm -rf /home/u376338418/public_html/rrc/*"
          scp -r ./* u376338418@88.223.85.159:/home/u376338418/public_html/rrc/
